### ISSUE TITLE
Fail a Jepsen run on an assertion failure

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/jepsen.dqlite#32]
Investigate if Jepsen marks the run as failed when a run triggers an assertion. If not, make it fail.

**Comment by cole-miller** [comment]
We do have a checker for assertion failures:

https://github.com/canonical/jepsen.dqlite/blob/da1d1c91c94defca60472cf2a63f6efbe6a756e3/src/jepsen/dqlite/db.clj#L196-L212

Probably worth making sure it will check everything we care about, though.
