### ISSUE TITLE
Set/stop job runs out of memory

### ISSUE THREAD

**Issue by cole-miller** [canonical/jepsen.dqlite#67]
Since #65 the `--workload set --nemesis stop` jobs regularly run out of memory during the analysis stage (in Jepsen code, not raft or dqlite). We might need to set a lower time limit for those jobs or find another way to address the issue.

**Comment by MathieuBordere** [comment]
Should we revert #65 for now? My feeling is that we are currently getting enough new information out of the Jepsen runs and that the time spent fixing the issues from the upgrade is maybe not super useful right now.

**Comment by MathieuBordere** [comment]
If the `set  / stop` combination can be solved by lowering the time limit and it's the only issue due to the upgrade, reverting is probably not needed.
